# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: da7ed9711d38257a9eb19310e101c133196599f50e7ea4f0498d34169f708f6fd51a851ca63456f93df26550b3e0a5e469b267b81907c32bb3c9b5b64804fd77

test:
  secret_key_base: 3e1464062c716e85d5e86d89a6be9a78417d5bca5f8b648a3e07f69f35a6e64977c406262ae832800a830f531faf040a4d5f61917f8e967fe2ad6f3014bc92ad

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
